version: "3.9"
services:
  rethinkdb:
    image: rethinkdb:2.4.2
    ports:
      - "0.0.0.0:28015:28015"
      - "0.0.0.0:8070:8080"
  dev:
    build: .
    command: sleep 1000000000
    volumes:
      - .:/app
    working_dir: /app
    user: "1000:1000"
    depends_on:
      - rethinkdb
  runner1:
    build: .
    image: test
    command:
      - '--db'
      - 'rethinkdb'
      - '--total-partitions'
      - '3'
      - '--current-partition'
      - '0'
      - '--total-workers'
      - '32'
      - '--host'
      - 'rethinkdb'
      - --worker-timeout-seconds
      - '60'
      - --worker-grace-period-seconds
      - '10'
      - --changefeed-buffer-size
      - '250000'
    environment:
      AMP_LOG_COLOR: '1'
    depends_on:
      - rethinkdb
    restart: always
    cap_add:
      - SYS_ADMIN
  runner2:
    restart: always
    build: .
    image: test
    command:
      - '--db'
      - 'rethinkdb'
      - '--total-partitions'
      - '3'
      - '--current-partition'
      - '1'
      - '--total-workers'
      - '32'
      - '--host'
      - 'rethinkdb'
      - --worker-timeout-seconds
      - '60'
      - --worker-grace-period-seconds
      - '10'
      - --changefeed-buffer-size
      - '250000'
    environment:
      AMP_LOG_COLOR: '1'
    depends_on:
      - rethinkdb
    cap_add:
      - SYS_ADMIN
  runner3:
    restart: always
    build: .
    image: test
    command:
      - '--db'
      - 'rethinkdb'
      - '--total-partitions'
      - '3'
      - '--current-partition'
      - '2'
      - '--total-workers'
      - '32'
      - '--host'
      - 'rethinkdb'
      - --worker-timeout-seconds
      - '60'
      - --worker-grace-period-seconds
      - '10'
      - --changefeed-buffer-size
      - '250000'
    environment:
      AMP_LOG_COLOR: '1'
    cap_add:
      - SYS_ADMIN
    depends_on:
      - rethinkdb
