name: build-cli
on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build php
        run: cli/build-php.sh
