name: Package Cleanup
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  dangling-images:
    name: Clean up dangling images
    runs-on: self-hosted
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: runtime
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
  old-test-images:
    name: Clean up test images
    runs-on: self-hosted
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'runtime-tests'
          package-type: 'container'
          min-versions-to-keep: 10
